### ISSUE TITLE
Drop down list for entries

### ISSUE THREAD

**Issue by artkpv** [jupj/vim-timeclock#1]
Thanks for the plugin. This is to request a feature, to be able to choose tasks in a drop down list for completions. It can be omnifunc

**Comment by jupj** [comment]
Thanks for the feedback, this is doable.

The completion could list tasks/accounts from the active timeclock file.
It could use Vim's builtin [fuzzy matching](https://vimhelp.org/pattern.txt.html#fuzzy-matching) to search for accounts.
